name: Auto Obfuscate edgetunnel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *" # 每天凌晨 2 点 (UTC+8)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 必须先检出当前仓库，以保留 .git 目录，为后续提交做准备
      - name: Checkout current repository
        uses: actions/checkout@v6

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      # 3. 安装混淆工具
      - name: Install obfuscator
        run: npm install -g javascript-obfuscator

      # 4. 从 odaychina/edgetunnel 拉取最新源文件
      - name: Download Source File
        run: |
          wget -O origin.js https://raw.githubusercontent.com/odaychina/edgetunnel/main/_worker.js

      # 5. 执行轻量级混淆
      - name: Obfuscate JS
        run: |
          javascript-obfuscator origin.js --output _worker.js \
          --compact true \
          --string-array true \
          --string-array-encoding 'base64' \
          --string-array-threshold 0.75 \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --transform-object-keys true

      # 6. 提交更改
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: main
          commit_message: '🤖 Auto obfuscate'
          file_pattern: _worker.js 
